# server:
#   port: 5454

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/food
#     username: root
#     password:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: phungtoan872@gmail.com
#     password: vlpfyqqlikmjfcpr
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#   servlet:
#     multipart:
#       max-file-size: 10MB
#       max-request-size: 10MB
#   resources:
#     static-locations:
#       - classpath:/static/
#       - file:uploads/images/

#   thymeleaf:
#     prefix: classpath:/templates/
#     suffix: .html
#     mode: HTML
#     encoding: UTF-8
#     cache: false

#   jackson:
#     serialization:
#       write-dates-as-timestamps: false
#     deserialization:
#       adjust-dates-to-context-time-zone: false

# stripe:
#   api:
#     key:
